//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sputnic1._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bar
    {
        public int Number { get; set; }
        public string Name { get; set; }
        public string Stock { get; set; }
        public string Price { get; set; }
    }
}
