//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sputnic1._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        public int Number { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public string Patronymic { get; set; }
        public Nullable<int> Balance { get; set; }
        public string Number_Telephone { get; set; }
        public string Login { get; set; }
    }
}
