//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sputnic1._1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Frolov_DiplomEntities : DbContext
    {

        private static Frolov_DiplomEntities current;

        public Frolov_DiplomEntities()
            : base("name=Frolov_DiplomEntities")
        {
        }

        public static Frolov_DiplomEntities GetContext()
        {
            if (current == null)
                current = new Frolov_DiplomEntities();
            return current;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Bar> Bar { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Pro_PC> Pro_PC { get; set; }
        public virtual DbSet<Standart_PC> Standart_PC { get; set; }
        public virtual DbSet<VIp_PC> VIp_PC { get; set; }
        public virtual DbSet<Packe> Packe { get; set; }
        public virtual DbSet<Logs> Logs { get; set; }
    }
}
