//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sputnic1._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Standart_PC
    {
        public int Number { get; set; }
        public string Name_PC { get; set; }
        public int Price_1h { get; set; }
        public string Name_acaunt { get; set; }
        public string State { get; set; }
    }
}
